#!/usr/bin/env python3
"""Summarize Phase-1 DFT final-relax outcomes and recommend next actions.

This merges:
- the Phase-1 batch manifest generated by ``step4.9.3``
- the task-level result summary CSV already produced for the finished jobs

The output is intended to play the same role as the LAMMPS-side shard
postprocessing tables: one row per task with a compact scientific diagnosis,
an operational next action, and an explicit note on whether the task should
advance to formal DFT-NEB preparation.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--batch-manifest-csv",
        type=Path,
        default=Path("data_center/step4.9.3_phase1_final_relax_batch_manifest_formal_v1.csv"),
    )
    parser.add_argument(
        "--result-summary-csv",
        type=Path,
        default=Path("data_center/step4.9.4_phase1_final_relax_result_summary_formal_v1.csv"),
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=Path("data_center/step4.9.5_phase1_final_relax_postcheck_summary_formal_v1.csv"),
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError(f"No rows to write for {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def as_bool(raw: str) -> bool:
    return str(raw).strip().lower() == "true"


def build_result_index(rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    return {row["job_dir"]: row for row in rows}


def classify_final_relax(result: dict[str, str]) -> tuple[str, str]:
    reached_required_accuracy = as_bool(result["reached_required_accuracy"])
    hit_nsw_limit = as_bool(result["hit_nsw_limit"])
    scientifically_usable = as_bool(result["scientifically_usable_final_endpoint"])

    if reached_required_accuracy and scientifically_usable and not hit_nsw_limit:
        return (
            "converged",
            "Reached the target force criterion and produced a usable relaxed final endpoint.",
        )
    if hit_nsw_limit and scientifically_usable:
        return (
            "hit_nsw_limit_but_usable",
            "Hit the ionic-step limit, but the endpoint remains scientifically usable; continue with the dedicated rerun rather than promoting this result to formal NEB.",
        )
    if scientifically_usable:
        return (
            "usable_without_required_accuracy",
            "Produced a usable endpoint, but did not cleanly satisfy the intended relaxation criterion.",
        )
    return (
        "not_yet_usable",
        "Did not clearly produce a scientifically usable relaxed final endpoint.",
    )


def classify_next_action(
    batch_row: dict[str, str],
    result: dict[str, str],
    rerun_dir: Path,
) -> tuple[str, str]:
    dft_action = batch_row["dft_action"]
    hit_nsw_limit = as_bool(result["hit_nsw_limit"])
    reached_required_accuracy = as_bool(result["reached_required_accuracy"])
    scientifically_usable = as_bool(result["scientifically_usable_final_endpoint"])

    rerun_submit_log = rerun_dir / "submit.log"
    rerun_exists = rerun_dir.exists()
    rerun_submitted = rerun_submit_log.exists()

    if hit_nsw_limit:
        if rerun_submitted:
            return (
                "wait_rerun_result",
                "The original final-relax hit the NSW limit and a rerun has already been submitted.",
            )
        if rerun_exists:
            return (
                "review_rerun_dir",
                "A rerun directory exists, but no submit.log was found yet.",
            )
        return (
            "prepare_rerun",
            "The original final-relax hit the NSW limit and should be continued from CONTCAR.",
        )

    if dft_action != "full_neb":
        return (
            "stop_after_phase1",
            "This shortlist item was explicitly marked as endpoint-adjudication only; do not auto-promote it to formal NEB.",
        )

    if reached_required_accuracy and scientifically_usable:
        return (
            "prepare_formal_neb",
            "Converged final endpoint and shortlist intent both support formal DFT-NEB preparation.",
        )

    if scientifically_usable:
        return (
            "manual_review_before_neb",
            "The endpoint appears usable, but the relaxation criterion was not cleanly satisfied; review before generating formal NEB.",
        )

    return (
        "hold_for_review",
        "Do not advance to formal NEB until the final endpoint issue is resolved.",
    )


def derive_rerun_dir(final_relax_dir: Path) -> Path:
    name = final_relax_dir.name
    if name.endswith("__final_relax_hpc"):
        return final_relax_dir.with_name(name[: -len("__final_relax_hpc")] + "__final_relax_rerun_hpc")
    return final_relax_dir.with_name(f"{name}__final_relax_rerun_hpc")


def main() -> None:
    args = parse_args()
    batch_rows = read_csv_rows(args.batch_manifest_csv)
    result_rows = read_csv_rows(args.result_summary_csv)
    result_index = build_result_index(result_rows)

    out_rows: list[dict[str, Any]] = []
    for batch_row in batch_rows:
        final_relax_dir = Path(batch_row["final_relax_dir"])
        job_dir = final_relax_dir.name
        result = result_index.get(job_dir)
        if result is None:
            raise KeyError(f"Missing result-summary row for {job_dir}")

        rerun_dir = derive_rerun_dir(final_relax_dir)
        final_relax_status, final_relax_note = classify_final_relax(result)
        next_action, next_action_note = classify_next_action(batch_row, result, rerun_dir)

        out_rows.append(
            {
                "phase": batch_row["phase"],
                "submission_rank": batch_row["submission_rank"],
                "event_pair_key": batch_row["event_pair_key"],
                "system_id": batch_row["system_id"],
                "formula": batch_row["formula"],
                "event_type": batch_row["event_type"],
                "event_family": batch_row["event_family"],
                "story_role": batch_row["story_role"],
                "dft_action": batch_row["dft_action"],
                "phase1_goal": batch_row["phase1_goal"],
                "phase2_followup": batch_row["phase2_followup"],
                "site_a": batch_row["site_a"],
                "site_b": batch_row["site_b"],
                "job_id": result["job_id"],
                "final_relax_dir": str(final_relax_dir),
                "final_relax_contcar": str(final_relax_dir / "CONTCAR"),
                "scaffold_dir": batch_row["scaffold_dir"],
                "rerun_dir": str(rerun_dir),
                "rerun_submit_log_exists": rerun_dir.joinpath("submit.log").exists(),
                "ionic_steps": result["ionic_steps"],
                "reached_required_accuracy": result["reached_required_accuracy"],
                "hit_nsw_limit": result["hit_nsw_limit"],
                "scientifically_usable_final_endpoint": result["scientifically_usable_final_endpoint"],
                "final_max_force_norm_eVA": result["final_max_force_norm_eVA"],
                "final_max_force_component_eVA": result["final_max_force_component_eVA"],
                "final_free_energy_eV": result["final_free_energy_eV"],
                "final_relax_status": final_relax_status,
                "final_relax_note": final_relax_note,
                "phase2_decision": next_action,
                "phase2_decision_note": next_action_note,
            }
        )

    write_csv(args.out_csv, out_rows)

    counts: dict[str, int] = {}
    for row in out_rows:
        key = str(row["phase2_decision"])
        counts[key] = counts.get(key, 0) + 1

    print(f"[OK] wrote phase1 final-relax postcheck summary: {args.out_csv.resolve()}")
    for key in sorted(counts):
        print(f"  - {key}: {counts[key]}")


if __name__ == "__main__":
    main()
